version: '3'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elastic_search/Dockerfile
    environment:
      - ES_SETTING_DISCOVERY_TYPE=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=1234
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elastic_search/volumes/home:/home
      - ./docker/elastic_search/volumes/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/RabbitMQ/Dockerfile
    ports:
        - 5672:5672
        - 15672:15672

  search-app:
    build: 
      context: .
      dockerfile: ./docker/searchapp/Dockerfile
    container_name: 'searchapp'
    ports:
      - 3000:3000
    volumes:
      - ./src/Apps/Search:/home/node/app

  backoffice:
    build: 
      context: .
      dockerfile: ./docker/backoffice/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./src/Apps/Backoffice/ui:/home/node/app

  backendapp:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src/Apps/Backoffice/Backend:/var/www/html

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: document
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql 